name: Auto Scrape M3U8 Links

on:
  schedule:
    # প্রতি ৬ ঘণ্টা পর পর অটোমেটিক চলবে (Cron syntax)
    - cron: '0 */6 * * *'
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/checkout@v3
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper Script
      run: python scraper.py

    - name: Commit and Push Updated M3U File
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.m3u
        git commit -m "Auto update playlist.m3u" || exit 0
        git push
